version: '3.8'

services:
  eureka-server:
    build: ./eureka
    ports:
      - "8761:8761"

  api-gateway:
    build: ./gateway
    ports:
      - "8080:8080"
    depends_on:
      - eureka

  user-service:
    build: ./user
    ports:
      - "8081:8080"
    depends_on:
      - eureka
      - mongodb

  post-service:
    build: ./post
    ports:
      - "8082:8080"
    depends_on:
      - eureka
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
